### ISSUE TITLE
Requesting "CVV help" images

### ISSUE THREAD

**Issue by fulldecent** [aaronfagan/svg-credit-card-payment-icons#3]
Requesting please one image for this situation

* Please enter the three digit code on the back of your card

And one for

* Please enter the four digit code on the front of your Amex

The new graphic need not have English words on it. But it should please have an arrow, box or some other highlighting to indicate the respective part of the card.

---

We currently use these two graphics respectively:

![card-discover-mastercard-visa](https://user-images.githubusercontent.com/382183/60300833-d89fa600-98fd-11e9-836b-90c62a47ba1d.png)
![card-amex](https://user-images.githubusercontent.com/382183/60300832-d89fa600-98fd-11e9-9334-9d3051ac374c.png)

**Comment by fulldecent** [comment]
United Way has these

https://app.mobilecause.com/assets/icons/cc_cvv_icon.svg

https://app.mobilecause.com/assets/icons/cc_amex_icon.svg

**Comment by aaronfagan** [comment]
Apparently I need to turn on notifications for issues on this repo.

Sorry I missed this! I will look at putting something together for this. Alternatively, open to pull requests!

**Comment by aaronfagan** [comment]
OK, I think this can be achieved by adding a red circle to the existing "Security Code" icon. Although im not sure that would specifically be beneficial to this project.

Ill open voting on this - if you would like to see this, please give @fulldecent initial request a +1!

Thanks!
