### ISSUE TITLE
GNU License

### ISSUE THREAD

**Issue by djaax** [aaronfagan/svg-credit-card-payment-icons#6]
Your payment icons look great, @aaronfagan! However, I cannot use them in my project because of the limiting GNU license which would force me to distribute my software under the same open source license. Have you thought about licensing your icons under a less restrictive license such as MIT for wider usage? I totally understand if you like not to.

**Comment by aaronfagan** [comment]
Im not married to the licensing that i've chosen - it was more of a placeholder when I set up this repo.

Any suggestions to get the licensing wide open? Is MIT the best option?

**Comment by aaronfagan** [comment]
Hey again @djaax ! After some review, I've changed our license over to Apache 2.0 (https://github.com/aaronfagan/svg-credit-card-payment-icons/blob/master/LICENSE).

Please let me know if this enables your usage, as I would very much like to enable as many third-party projects and users as I can!

**Comment by djaax** [comment]
Hey @aaronfagan! Thanks for considering changing the license. I think the Apache license is a great choice. This allows me to include your icons in my project. Thanks you! And again, great work!
