### ISSUE TITLE
Update mastercard and maestro brand design

### ISSUE THREAD

**Issue by ryuran** [aaronfagan/svg-credit-card-payment-icons#7]
Hello.

Logo of mastercard and maestro card changed recently.
https://medium.com/@inkbotdesign/history-of-the-mastercard-logo-design-evolution-d81b523f06a9

So card icons should be updated following the new guidelines :
https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html
https://brand.mastercard.com/brandcenter/other-marks.html

**Comment by aladeuil** [comment]
Also 
Visa : https://usa.visa.com/run-your-business/accept-visa-payments/posguidelines.html
Diners Club : http://sa.dinersclubinternational.com/assets/DCI_logo_guide.pdf
Amex : https://secure.americanexpress.com.bh/merchants/website-assets/downloads/American_Express_Guidelines.pdf

**Comment by aaronfagan** [comment]
Long awaited, this is now done and merged.
