### ISSUE TITLE
any plans to create a react api for it?

### ISSUE THREAD

**Issue by Mazuh** [aaronfagan/svg-credit-card-payment-icons#9]
@aaronfagan,  I didn't see yet a react lib with so many options like your icons. There is any lib using your icons? And how do you feel about it?

(fyi, I didnt't found one, so I created a private component in my project and I was planning to publish it, but I don't want to do something you don't want to or already exists.)

**Comment by aaronfagan** [comment]
Hi @Mazuh !

If you have built a react component you want to publish/open-source, please do! Only thing required is a credit reference back to my repo/icons.

Thanks for checking! Also, please send over your stuff, once its published! Ide love to take a look (might actually start compiling a list of other public things using these icons).

Cheers!
